version: "3.3"
services:
    proxyserver:
        build:
            context: ./proxy
        ports:
            - "8080:80"
            - "8443:443"
    theia:
        build:
            context: .
        ports:
            - "30000:3000"